"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, BookOpen, Check, CheckCircle2, ChevronLeft, CircleAlert, ClipboardCheck, Copy, Expand, FileQuestion, Flag, HeartHandshake, Lightbulb, MessageSquareText, Minimize, Quote, RotateCcw, Sparkles, X } from "lucide-react";
import type { Activity, Slide } from "../types";
import { content, findQuiz, nextSlideIndex, scoreQuiz } from "../lib/content";
import { useUser } from "./UserProvider";

export function LearningView({ dayId, moduleId, initialSlide = 0 }: { dayId: string; moduleId: string; initialSlide?: number }) {
  const { data, update, notify } = useUser(); const day=content.days.find(d=>d.id===dayId); const lessonModule=day?.modules.find(m=>m.id===moduleId);
  const [index,setIndex]=useState(Math.min(Math.max(initialSlide,0),(lessonModule?.slides.length||1)-1)); const [notes,setNotes]=useState(false); const [presenting,setPresenting]=useState(false);
  const slide=lessonModule?.slides[index]; const completed=slide?data.completedSlides.includes(slide.id):false; const pct=lessonModule?Math.round(((index+1)/lessonModule.slides.length)*100):0; const slideCount=lessonModule?.slides.length||0;
  const move=(direction:"next"|"previous")=>setIndex(i=>nextSlideIndex(i,slideCount,direction));
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==="ArrowLeft")setIndex(i=>nextSlideIndex(i,slideCount,"next"));if(e.key==="ArrowRight")setIndex(i=>nextSlideIndex(i,slideCount,"previous"));};addEventListener("keydown",handler);return()=>removeEventListener("keydown",handler);},[slideCount]);
  useEffect(()=>{if(slide)update(c=>({...c,lastVisited:{dayId,moduleId,slideIndex:index}}));},[index,dayId,moduleId,slide,update]);
  if(!day||!lessonModule||!slide)return <div className="error-state"><CircleAlert/><h1>تعذر العثور على هذا المحتوى</h1><a href="/course">العودة إلى البرنامج</a></div>;
  const markComplete=()=>{update(c=>({...c,completedSlides:c.completedSlides.includes(slide.id)?c.completedSlides:[...c.completedSlides,slide.id]}));notify("تم إكمال الشاشة");};
  const toggleBookmark=()=>{const on=data.bookmarks.includes(slide.id);update(c=>({...c,bookmarks:on?c.bookmarks.filter(x=>x!==slide.id):[...c.bookmarks,slide.id]}));notify(on?"تمت الإزالة من المفضلة":"تمت الإضافة للمفضلة");};
  const togglePresent=async()=>{if(!presenting)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.();setPresenting(!presenting)};
  return <div className={`learning-shell ${presenting?"presenting":""}`}>
    <header className="learn-header no-print"><a className="brand compact" href="/"><span className="brand-mark">أ</span><b>أثر</b></a><div className="breadcrumbs"><span>{day.title}</span><ChevronLeft/><b>{lessonModule.title}</b></div><button className="secondary-btn compact-btn" onClick={togglePresent}>{presenting?<Minimize/>:<Expand/>}{presenting?"إنهاء العرض":"وضع العرض"}</button></header>
    <div className="learn-progress no-print"><b style={{width:`${pct}%`}}/></div>
    <div className="learn-layout"><aside className="module-nav no-print"><span className="kicker">محتويات المحور</span><h2>{lessonModule.title}</h2><p>{lessonModule.description}</p><div>{lessonModule.slides.map((s,i)=><button key={s.id} onClick={()=>setIndex(i)} className={i===index?"active":data.completedSlides.includes(s.id)?"done":""}><span>{data.completedSlides.includes(s.id)?<Check/>:i+1}</span><em>{s.title}</em></button>)}</div></aside>
      <main className="slide-stage"><div className="slide-card"><SlideRenderer slide={slide}/></div><div className="learn-controls no-print"><div><button className={`tool-btn ${data.bookmarks.includes(slide.id)?"active":""}`} onClick={toggleBookmark}><Bookmark/>المفضلة</button><button className="tool-btn" onClick={()=>setNotes(true)}><MessageSquareText/>ملاحظاتي</button></div><div className="pagination"><button onClick={()=>move("previous")} disabled={index===0}><ArrowRight/> السابق</button><span><b>{index+1}</b> / {lessonModule.slides.length}</span><button onClick={()=>move("next")} disabled={index===lessonModule.slides.length-1}>التالي <ArrowLeft/></button></div><button className={`complete-btn ${completed?"done":""}`} onClick={markComplete}>{completed?<CheckCircle2/>:<Check/>}{completed?"مكتملة":"إكمال"}</button></div></main>
    </div>
    {notes&&<div className="drawer-backdrop"><button className="drawer-dismiss" aria-label="إغلاق الملاحظات" onClick={()=>setNotes(false)}/><aside className="notes-drawer"><button className="drawer-close" onClick={()=>setNotes(false)}><X/></button><span className="kicker">مرتبطة بهذه الشاشة</span><h2>ملاحظاتي</h2><p>{slide.title}</p><textarea rows={14} value={data.notes[slide.id]||""} onChange={e=>{const v=e.target.value;update(c=>({...c,notes:{...c.notes,[slide.id]:v}}))}} onBlur={()=>notify("تم حفظ الملاحظة")} placeholder="اكتب ما تريد تذكره..."/><small><Check/> حفظ تلقائي على جهازك</small></aside></div>}
  </div>;
}

export function SlideRenderer({slide}:{slide:Slide}) {
  const iconMap:Record<string,any>={quote:Quote,warning:CircleAlert,tip:Lightbulb,definition:BookOpen,reflection:HeartHandshake,prompt:Sparkles,"case-study":Flag,activity:ClipboardCheck,quiz:FileQuestion}; const Icon=iconMap[slide.type]||Sparkles;
  if(slide.type==="activity"&&slide.activity)return <ActivitySlide activity={slide.activity}/>;
  if(slide.type==="quiz"&&slide.quizId)return <QuizSlide quizId={slide.quizId}/>;
  if(slide.type==="project-task")return <div className="slide-centered"><span className="slide-icon"><Flag/></span><h1>{slide.title}</h1><p>{slide.body}</p><a className="primary-btn" href={slide.href}>فتح مختبر المشروع <ArrowLeft/></a></div>;
  if(slide.type==="title")return <div className="slide-title"><span className="kicker">{slide.eyebrow}</span><h1>{slide.title}</h1><p>{slide.body}</p><div className="title-rule"><i/><span>تعلم • طبّق • قِس</span></div></div>;
  if(slide.type==="comparison")return <div><SlideHead slide={slide}/><div className="comparison-grid">{slide.columns?.map((c:any,i)=><article key={i}><span>0{i+1}</span><h3>{c.title}</h3><p>{c.body}</p></article>)}</div></div>;
  if(slide.type==="cards")return <div><SlideHead slide={slide}/><div className="slide-cards">{slide.items?.map((x:any,i)=><article key={i}><Sparkles/><h3>{x.title}</h3><p>{x.body}</p></article>)}</div></div>;
  if(slide.type==="steps"||slide.type==="timeline")return <div><SlideHead slide={slide}/><ol className="steps-list">{slide.items?.map((x:any,i)=><li key={i}><span>{i+1}</span><p>{String(x)}</p></li>)}</ol></div>;
  if(slide.type==="checklist")return <div><SlideHead slide={slide}/><ul className="check-list">{slide.items?.map((x:any,i)=><li key={i}><Check/><span>{String(x)}</span></li>)}</ul></div>;
  if(slide.type==="stats")return <div><SlideHead slide={slide}/><div className="slide-stats">{slide.items?.map((x:any,i)=><article key={i}><b>{x.value}</b><span>{x.label}</span></article>)}</div>{slide.dataset&&<MiniBars/>}</div>;
  if(slide.type==="table")return <div><SlideHead slide={slide}/><div className="table-wrap"><table><thead><tr>{slide.headers?.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{slide.rows?.map((row,i)=><tr key={i}>{row.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div></div>;
  if(slide.type==="example")return <div><SlideHead slide={slide}/><div className="example-grid"><article className="bad"><small>ضعيف</small><p>{slide.bad}</p></article><article className="good"><small>محسّن</small><p>{slide.good}</p></article></div></div>;
  if(["warning","tip","definition","reflection","prompt","case-study","quote","content","intro","discussion","question","summary","resources","divider","worksheet","image","video"].includes(slide.type))return <div className={`prose-slide type-${slide.type}`}><span className="slide-icon"><Icon/></span><SlideHead slide={slide}/>{slide.body&&<p className="lead">{slide.body}</p>}{slide.items&&<ul>{slide.items.map((x:any,i)=><li key={i}>{typeof x==="string"?x:x.title}</li>)}</ul>}{slide.type==="prompt"&&<CopyPrompt text={slide.body||""}/>}</div>;
  return <div className="prose-slide"><SlideHead slide={slide}/><p>{slide.body||"تعذر عرض محتوى هذه الشاشة. راجع ملف البيانات."}</p></div>;
}
function SlideHead({slide}:{slide:Slide}){return <header className="slide-heading"><span className="kicker">{typeLabel(slide.type)}</span><h1>{slide.title}</h1></header>}
function typeLabel(t:string){return ({content:"فكرة أساسية",comparison:"مقارنة",steps:"خطوات عملية",timeline:"مسار",cards:"نظرة شاملة",checklist:"قائمة تحقق",stats:"المؤشرات",table:"البيانات",example:"مثال تطبيقي",warning:"انتبه",tip:"نصيحة عملية",definition:"مصطلح",reflection:"تأمل",prompt:"Prompt جاهز","case-study":"دراسة حالة",summary:"خلاصة"} as Record<string,string>)[t]||"شاشة تدريبية"}
function CopyPrompt({text}:{text:string}){const {notify}=useUser();return <button className="copy-btn" onClick={()=>navigator.clipboard.writeText(text).then(()=>notify("تم النسخ"))}><Copy/>نسخ المطالبة</button>}
function MiniBars(){return <div className="mini-chart" aria-label="رسم أعمدة للمستفيدين"><i style={{height:"76%"}}/><i style={{height:"34%"}}/><i style={{height:"65%"}}/><i style={{height:"49%"}}/><span>مقارنة عدد المستفيدين بين المبادرات</span></div>}

function ActivitySlide({activity}:{activity:Activity}) { const {data,update,notify}=useUser(); const answers=data.activityAnswers[activity.id]||{}; const complete=data.completedActivities.includes(activity.id); const change=(id:string,value:unknown)=>update(c=>({...c,activityAnswers:{...c.activityAnswers,[activity.id]:{...(c.activityAnswers[activity.id]||{}),[id]:value}}}));
  return <div className="activity-slide"><span className="kicker">نشاط تطبيقي • {activity.duration}</span><h1>{activity.title}</h1><p>{activity.description}</p><div className="instruction"><ClipboardCheck/><span>{activity.instructions}</span></div><div className="activity-fields">{activity.fields.map(f=><label key={f.id}><span>{f.label}</span>{f.type==="textarea"?<textarea rows={4} value={String(answers[f.id]||"")} onChange={e=>change(f.id,e.target.value)} onBlur={()=>notify("تم الحفظ تلقائيًا")}/>:f.type==="select"?<select value={String(answers[f.id]||"")} onChange={e=>change(f.id,e.target.value)}><option value="">اختر...</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input value={String(answers[f.id]||"")} onChange={e=>change(f.id,e.target.value)} onBlur={()=>notify("تم الحفظ تلقائيًا")}/>}</label>)}</div>{activity.tips&&<div className="activity-tip"><Lightbulb/>{activity.tips.join(" • ")}</div>}<button className={`primary-btn ${complete?"success":""}`} onClick={()=>{update(c=>({...c,completedActivities:c.completedActivities.includes(activity.id)?c.completedActivities:[...c.completedActivities,activity.id]}));notify("تم إكمال النشاط")}}>{complete?<CheckCircle2/>:<Check/>}{complete?"النشاط مكتمل":"إكمال النشاط"}</button><small className="autosave"><Check/> تم الحفظ تلقائيًا</small></div>;
}

function QuizSlide({quizId}:{quizId:string}) { const {update}=useUser(); const quiz=findQuiz(quizId); const [answers,setAnswers]=useState<Record<string,string[]>>({}); const [submitted,setSubmitted]=useState(false); if(!quiz)return <div className="error-state">تعذر تحميل الاختبار.</div>;
  const result=submitted?scoreQuiz(quiz,answers):null; const choose=(qid:string,option:string,multi:boolean)=>setAnswers(a=>{const current=a[qid]||[];return {...a,[qid]:multi?(current.includes(option)?current.filter(x=>x!==option):[...current,option]):[option]}});
  return <div className="quiz-slide"><span className="kicker">اختبار قصير</span><h1>{quiz.title}</h1>{quiz.questions.map((q,i)=>{const isCorrect=result&&scoreQuiz({id:"x",title:"x",questions:[q]},answers).score===1;return <fieldset key={q.id}><legend><span>{i+1}</span>{q.question}</legend><div className="quiz-options">{q.options.map(option=><label key={option} className={answers[q.id]?.includes(option)?"selected":""}><input type={q.type==="multiple-choice"?"checkbox":"radio"} name={q.id} checked={answers[q.id]?.includes(option)||false} onChange={()=>choose(q.id,option,q.type==="multiple-choice")}/><i>{answers[q.id]?.includes(option)&&<Check/>}</i>{option}</label>)}</div>{submitted&&<div className={`feedback ${isCorrect?"correct":"wrong"}`}><b>{isCorrect?"إجابة صحيحة":"راجع الإجابة"}</b><p>{q.explanation}</p></div>}</fieldset>})}{!submitted?<button className="primary-btn" disabled={Object.keys(answers).length<quiz.questions.length} onClick={()=>{const r=scoreQuiz(quiz,answers);setSubmitted(true);update(c=>({...c,quizResults:{...c.quizResults,[quiz.id]:!c.quizResults[quiz.id]||c.quizResults[quiz.id].percentage<r.percentage?r:c.quizResults[quiz.id]}}))}}>عرض النتيجة</button>:<div className="quiz-result"><ProgressBadge value={result?.percentage||0}/><div><h2>{result?.score} من {result?.total}</h2><p>حُفظت أفضل نتيجة لك.</p><button className="link-btn" onClick={()=>{setAnswers({});setSubmitted(false)}}><RotateCcw/>إعادة الاختبار</button></div></div>}</div>;
}
function ProgressBadge({value}:{value:number}){return <div className="score-badge">{value}%</div>}

export function AssessmentView({quizId}:{quizId:string}){const quiz=findQuiz(quizId);return <div className="assessment-page"><header><a href="/" className="brand compact"><span className="brand-mark">أ</span><b>أثر</b></a><a href="/course">تخطي الآن</a></header><main><span className="kicker">تقييم اختياري</span><h1>{quiz?.title||"التقييم"}</h1><p>يساعدك هذا التقييم على معرفة نقطة البداية. لن يمنعك من دخول البرنامج.</p><div className="slide-card"><QuizSlide quizId={quizId}/></div><a className="primary-btn assessment-next" href="/course">الانتقال إلى البرنامج <ArrowLeft/></a></main></div>}
