"use client";
import { useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowUpLeft, Award, BookMarked, BookOpen, Check, ChevronLeft, ClipboardCheck, Copy, Download, FileText, FolderKanban, Gauge, Moon, Printer, RotateCcw, Search, ShieldCheck, Sparkles, Sun, Upload, WandSparkles } from "lucide-react";
import { AppShell } from "./AppShell";
import { useUser } from "./UserProvider";
import { allModules, content, courseProgress, dayProgress, moduleProgress, totalActivities, totalSlides } from "../lib/content";
import { clearUserData, initialUserData, validateBackup } from "../services/storage";

function ProgressRing({ value }: { value: number }) { return <div className="progress-ring" style={{ "--p": `${value * 3.6}deg` } as React.CSSProperties}><span>{value}%</span></div>; }

export function HomeView() {
  const { data } = useUser(); const progress = courseProgress(data.completedSlides); const next = data.lastVisited;
  const resume = next ? `/learn/${next.dayId}/${next.moduleId}?slide=${next.slideIndex}` : "/assessment/pre-assessment";
  return <AppShell current="/"><section className="hero container">
    <div className="hero-copy"><span className="kicker"><Sparkles size={16}/> رحلة تطبيقية من الفكرة إلى الأثر</span><h1>الذكاء الاصطناعي<br/><em>في القطاع غير الربحي</em></h1><p>{content.course.description}</p>
      <div className="hero-actions"><a href={resume} className="primary-btn">{next ? "متابعة من حيث توقفت" : "ابدأ التدريب"}<ArrowLeft size={18}/></a><a href="/course" className="secondary-btn">استعراض البرنامج</a></div>
      <div className="hero-meta"><span><b>3</b> أيام</span><span><b>9</b> محاور</span><span><b>{totalActivities}</b> أنشطة</span><span><b>18</b> ساعة</span></div>
    </div>
    <div className="hero-panel"><div className="orb orb-a"/><div className="orb orb-b"/><div className="hero-progress"><span>تقدمك في الرحلة</span><ProgressRing value={progress}/><small>{progress ? "استمر، كل خطوة تبني مشروعك" : "بداية هادئة، أثر ممتد"}</small></div><div className="floating-card"><Sparkles size={18}/><span>تعلم • طبّق • قِس</span></div></div>
  </section>
  <section className="quick-links container"><a href="/project"><FolderKanban/>المشروع النهائي</a><a href="/resources"><BookMarked/>المصادر</a><a href="/progress"><Gauge/>تقدمي</a><a href="/prompts"><WandSparkles/>مكتبة Prompts</a></section>
  <section className="container section"><div className="section-heading"><div><span className="kicker">الخطة التدريبية</span><h2>ثلاثة أيام. مسار واحد مترابط.</h2></div><a href="/course">عرض الخطة كاملة <ArrowUpLeft size={16}/></a></div>
    <div className="day-grid">{content.days.map((day) => { const p=dayProgress(day.id,data.completedSlides); return <a className="day-card" href={`/learn/${day.id}/${day.modules[0].id}`} key={day.id}><div className="day-number">0{day.dayNumber}</div><span className={`status ${p===100?"done":p>0?"active":""}`}>{p===100?"مكتمل":p>0?"قيد التنفيذ":"لم يبدأ"}</span><h3>{day.title}</h3><p>{day.description}</p><div className="day-tags"><span>{day.modules.length} محاور</span><span>{day.duration}</span></div><div className="linear"><b style={{width:`${p}%`}}/></div><small>{p}% إنجاز</small></a>})}</div>
  </section></AppShell>;
}

export function CourseView() { const {data}=useUser(); return <AppShell current="/course"><PageHero kicker="الخطة التدريبية" title="من الفهم إلى مشروع قابل للقياس" body="يتدرج المسار من الاستخدام المسؤول للذكاء الاصطناعي إلى تصميم مبادرة وتحليل أثرها."/>
  <section className="container timeline">{content.days.map((day)=><article className="timeline-day" key={day.id}><div className="timeline-index">اليوم<br/><b>{day.dayNumber}</b></div><div className="timeline-content"><div className="timeline-head"><div><h2>{day.title}</h2><p>{day.description}</p></div><span>{day.duration}</span></div>{day.modules.map((module,i)=><a className="module-row" key={module.id} href={`/learn/${day.id}/${module.id}`}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{module.title}</h3><p>{module.description}</p><small>{module.slides.length} شاشات • {module.duration}</small></div><div className="module-progress"><b>{moduleProgress(module.id,data.completedSlides)}%</b><ChevronLeft/></div></a>)}</div></article>)}</section></AppShell>; }

function PageHero({kicker,title,body}:{kicker:string;title:string;body:string}) { return <section className="page-hero container"><span className="kicker">{kicker}</span><h1>{title}</h1><p>{body}</p></section>; }

export function ProjectView() {
  const {data,update,notify}=useUser(); const [step,setStep]=useState(0); const item=content.project.steps[step]; const complete=content.project.steps.filter(s=>data.projectAnswers[s.id]?.trim()).length; const percent=Math.round(complete/content.project.steps.length*100);
  return <AppShell current="/project"><PageHero kicker="Project Lab" title="ابنِ مبادرتك، خطوة بخطوة" body="17 خطوة مترابطة، حفظ تلقائي، وتقرير نهائي جاهز للطباعة."/><section className="container project-layout">
    <aside className="project-steps"><div className="project-meter"><ProgressRing value={percent}/><div><b>{complete} من 17</b><small>خطوة مكتملة</small></div></div>{content.project.steps.map((s,i)=><button key={s.id} className={i===step?"active":""} onClick={()=>setStep(i)}><span>{data.projectAnswers[s.id]?.trim()?<Check/>:i+1}</span>{s.title}</button>)}</aside>
    <div className="project-editor"><span className="kicker">الخطوة {step+1} من 17</span><h2>{item.title}</h2><p>{item.prompt}</p><textarea rows={10} value={data.projectAnswers[item.id]||""} onChange={(e)=>{ const value=e.target.value; update(c=>({...c,projectAnswers:{...c.projectAnswers,[item.id]:value}})); }} onBlur={()=>notify("تم الحفظ تلقائيًا")} placeholder="اكتب مسودتك هنا..."/><small className="autosave"><Check size={14}/> تحفظ إجابتك تلقائيًا على هذا الجهاز</small><div className="editor-actions"><button className="secondary-btn" disabled={!step} onClick={()=>setStep(step-1)}>السابق</button>{step<16?<button className="primary-btn" onClick={()=>setStep(step+1)}>التالي <ArrowLeft size={17}/></button>:<a className="primary-btn" href="/project/report">عرض المشروع النهائي</a>}</div></div>
  </section></AppShell>;
}

export function ProjectReportView(){ const {data}=useUser(); return <AppShell><section className="report container"><div className="report-cover"><span className="kicker">المشروع النهائي</span><h1>{data.projectAnswers.idea||"مبادرتي المجتمعية"}</h1><p>إعداد: {data.profile.name||"متدرب المنصة"}</p><button className="secondary-btn no-print" onClick={()=>window.print()}><Printer size={17}/> طباعة / حفظ PDF</button></div>{content.project.steps.map((s,i)=><article key={s.id}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{s.title}</h2><p>{data.projectAnswers[s.id]||"لم تُكتب هذه الخطوة بعد."}</p></div></article>)}</section></AppShell>; }

export function ProgressView(){ const {data}=useUser(); const p=courseProgress(data.completedSlides); const projectDone=content.project.steps.filter(s=>data.projectAnswers[s.id]?.trim()).length; return <AppShell current="/progress"><PageHero kicker="لوحة التقدم" title="أثر صغير يتراكم كل يوم" body="هنا ترى ما أنجزته وما يستحق تركيزك في الخطوة التالية."/><section className="container stats-grid"><Stat icon={Gauge} label="تقدم البرنامج" value={`${p}%`}/><Stat icon={BookOpen} label="الشاشات المكتملة" value={`${data.completedSlides.length}/${totalSlides}`}/><Stat icon={ClipboardCheck} label="الأنشطة" value={`${data.completedActivities.length}/${totalActivities}`}/><Stat icon={FolderKanban} label="المشروع" value={`${projectDone}/17`}/></section><section className="container progress-panel"><h2>تقدم الأيام</h2>{content.days.map(day=><div className="progress-row" key={day.id}><span>{day.title}</span><div className="linear"><b style={{width:`${dayProgress(day.id,data.completedSlides)}%`}}/></div><b>{dayProgress(day.id,data.completedSlides)}%</b></div>)}<h2>أفضل نتائج الاختبارات</h2><div className="result-grid">{Object.entries(data.quizResults).length?Object.entries(data.quizResults).map(([id,r])=><div key={id}><span>{content.quizzes.find(q=>q.id===id)?.title||id}</span><b>{r.percentage}%</b></div>):<Empty text="ستظهر نتائج اختباراتك هنا بعد أول محاولة."/>}</div></section></AppShell>; }
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="stat-card"><Icon/><span>{label}</span><b>{value}</b></div>}

export function LibraryView({kind}:{kind:"prompts"|"glossary"|"resources"|"tools"}) { const {notify}=useUser(); const [query,setQuery]=useState("");
  const config={prompts:["مكتبة Prompts","مطالبات عملية قابلة للنسخ والتحسين","/prompts"],glossary:["قاموس المصطلحات","مرجع عربي مبسط للمفاهيم الأساسية","/glossary"],resources:["المصادر والقوالب","مراجع العمل التي ترافق رحلتك","/resources"],tools:["أدوات العمل","قوالب صغيرة تساعدك على التفكير والتنفيذ","/tools"]}[kind];
  const source=kind==="prompts"?content.prompts:kind==="glossary"?content.glossary:kind==="resources"?content.resources:[
    {title:"مولّد هدف SMART",description:"حوّل الهدف العام إلى صيغة قابلة للقياس.",url:"/project"},{title:"مراجع الخصوصية",description:"قائمة تحقق قبل إدخال أي بيانات في أداة AI.",url:"/learn/day-1/ai-foundations?slide=6"},{title:"حاسبة معدل التحويل",description:"قس انتقال الجمهور بين مراحل المسار.",url:"/learn/day-2/marketing?slide=4"},{title:"مصمم سلسلة الأثر",description:"اربط المدخلات بالمخرجات والنتائج والأثر.",url:"/project"}];
  const filtered=(source as any[]).filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));
  return <AppShell current={config[2]}><PageHero kicker={config[0]} title={config[0]} body={config[1]}/><section className="container library"><label className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث داخل المكتبة..."/></label><div className="library-grid">{filtered.map((item:any,i)=><article key={item.id||item.term||i}><span className="card-icon">{kind==="glossary"?<BookOpen/>:kind==="prompts"?<Sparkles/>:<FileText/>}</span><small>{item.category||item.en||"أداة تطبيقية"}</small><h2>{item.title||item.term}</h2><p>{item.text||item.definition||item.description}</p>{kind==="prompts"?<button className="copy-btn" onClick={()=>navigator.clipboard.writeText(item.text).then(()=>notify("تم النسخ"))}><Copy/>نسخ المطالبة</button>:item.url?<a href={item.url}>فتح <ArrowUpLeft/></a>:null}</article>)}</div>{!filtered.length&&<Empty text="لا توجد نتائج مطابقة."/>}</section></AppShell>;
}

export function NotesView(){ const {data,update,notify}=useUser(); const entries=Object.entries(data.notes).filter(([,v])=>v.trim()); return <AppShell><PageHero kicker="مساحتك الخاصة" title="ملاحظاتي" body="ملاحظاتك مرتبطة بالشاشات ومحفوظة على هذا الجهاز فقط."/><section className="container notes-list">{entries.length?entries.map(([id,value])=><article key={id}><small>{id}</small><textarea value={value} onChange={e=>update(c=>({...c,notes:{...c.notes,[id]:e.target.value}}))} onBlur={()=>notify("تم الحفظ")}/></article>):<Empty text="لم تضف ملاحظات بعد. افتح أي شاشة تدريب واضغط «ملاحظاتي»."/>}</section></AppShell>; }

export function SearchView(){ const [q,setQ]=useState(""); const results=useMemo(()=>q.trim()?allModules.flatMap(({day,module})=>module.slides.filter(s=>JSON.stringify(s).includes(q)).map(s=>({day,module,slide:s}))).slice(0,30):[],[q]); return <AppShell><PageHero kicker="بحث شامل" title="ابحث في محتوى الحقيبة" body="العناوين، الشروحات، الأمثلة، الأنشطة والمصطلحات."/><section className="container library"><label className="search-box large"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جرّب: الخصوصية، SMART، الأثر..."/></label>{q&&<p className="result-count">{results.length} نتيجة</p>}<div className="search-results">{results.map(({day,module,slide},i)=><a key={`${slide.id}-${i}`} href={`/learn/${day.id}/${module.id}?slide=${module.slides.findIndex(s=>s.id===slide.id)}`}><small>{day.title} ← {module.title}</small><h2>{slide.title}</h2><p>{slide.body||"محتوى تدريبي تفاعلي"}</p><ArrowUpLeft/></a>)}</div>{q&&!results.length&&<Empty text="لم نجد نتيجة. جرّب كلمة أقصر."/>}</section></AppShell>; }

export function SettingsView(){ const {data,update,notify}=useUser(); const fileRef=useRef<HTMLInputElement>(null); const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="training-backup.json";a.click();URL.revokeObjectURL(a.href);}; const importData=async(e:React.ChangeEvent<HTMLInputElement>)=>{try{const file=e.target.files?.[0];if(!file)return;const restored=validateBackup(JSON.parse(await file.text()));update(()=>restored);notify("تم استيراد النسخة بنجاح");}catch(err){notify(err instanceof Error?err.message:"حدث خطأ");}};
  return <AppShell><PageHero kicker="الإعدادات" title="اجعل التجربة تناسبك" body="المظهر والوصول والنسخ الاحتياطي — كل شيء يبقى على جهازك."/><section className="container settings"><div className="setting-card"><h2>المظهر</h2><div className="segmented">{(["light","dark","system"] as const).map(x=><button className={data.settings.theme===x?"active":""} onClick={()=>update(c=>({...c,settings:{...c.settings,theme:x}}))} key={x}>{x==="light"?<Sun/>:x==="dark"?<Moon/>:<Sparkles/>}{x==="light"?"فاتح":x==="dark"?"داكن":"النظام"}</button>)}</div></div><div className="setting-card"><h2>حجم الخط</h2><div className="segmented">{(["small","medium","large","xlarge"] as const).map((x,i)=><button className={data.settings.fontSize===x?"active":""} onClick={()=>update(c=>({...c,settings:{...c.settings,fontSize:x}}))} key={x}>{["صغير","متوسط","كبير","كبير جدًا"][i]}</button>)}</div><label className="switch"><input type="checkbox" checked={data.settings.animations} onChange={e=>update(c=>({...c,settings:{...c.settings,animations:e.target.checked}}))}/><span/> تشغيل الحركات</label></div><div className="setting-card"><h2>بياناتي</h2><p>صدّر تقدمك وإجاباتك قبل حذف بيانات المتصفح أو الانتقال لجهاز آخر.</p><div className="button-row"><button className="secondary-btn" onClick={exportData}><Download/>تصدير</button><button className="secondary-btn" onClick={()=>fileRef.current?.click()}><Upload/>استيراد</button><input hidden ref={fileRef} type="file" accept="application/json" onChange={importData}/><button className="danger-btn" onClick={async()=>{if(confirm("سيتم حذف كل تقدمك وإجاباتك. هل أنت متأكد؟")){await clearUserData();update(()=>initialUserData);location.href="/";}}}><RotateCcw/>مسح البيانات</button></div></div><div className="setting-card"><h2>حول البرنامج</h2><p>{content.course.title} — نسخة {content.course.version}. منصة محلية بلا حسابات أو تتبع شخصي.</p><button className="link-btn" onClick={()=>update(c=>({...c,profile:{...c.profile,onboarded:false}}))}>إعادة عرض شاشة الترحيب</button></div></section></AppShell>; }

export function PrivacyView(){return <AppShell><PageHero kicker="الخصوصية أولًا" title="بياناتك التدريبية لك" body="صُممت المنصة لتعمل دون حساب ودون إرسال تقدمك إلى خادم."/><section className="container prose"><ShieldCheck size={46}/><h2>ما الذي تحفظه المنصة؟</h2><p>تقدمك، إجابات الأنشطة والاختبارات، المشروع، الملاحظات والمفضلة محفوظة داخل متصفحك عبر التخزين المحلي وIndexedDB.</p><h2>ما الذي لا تفعله؟</h2><p>لا تطلب رقم هوية أو هاتف أو بريد، ولا ترسل إجاباتك إلى خادم. الاسم اختياري ويستخدم محليًا للشهادة والتخصيص.</p><h2>مسؤوليتك عن النسخة الاحتياطية</h2><p>حذف بيانات المتصفح أو استخدام جهاز آخر قد يفقدك التقدم. استخدم «تصدير بياناتي» من الإعدادات بانتظام.</p></section></AppShell>}

export function CertificateView(){const {data}=useUser();const p=courseProgress(data.completedSlides);return <AppShell><section className="certificate container"><div className="certificate-mark"><Award/></div><span>شهادة إتمام تدريبية</span><h1>{content.course.title}</h1><p>تشهد المنصة بأن</p><h2>{data.profile.name||"اسم المتدرب"}</h2><p>أتم رحلة تدريبية بمدة {content.course.duration}</p><div className="certificate-meta"><span>تاريخ الإصدار<br/><b>{new Intl.DateTimeFormat("ar-SA",{dateStyle:"long"}).format(new Date())}</b></span><span>نسبة الإكمال<br/><b>{p}%</b></span></div>{p<content.course.certificateThreshold?<div className="certificate-lock">تُتاح الشهادة عند إكمال {content.course.certificateThreshold}% من البرنامج.</div>:<button className="secondary-btn no-print" onClick={()=>window.print()}><Printer/>طباعة الشهادة</button>}<small>هذه شهادة إتمام صادرة من المنصة التدريبية وليست اعتمادًا رسميًا ما لم تعتمدها الجهة المقدمة للبرنامج.</small></section></AppShell>}
function Empty({text}:{text:string}){return <div className="empty"><BookOpen/><p>{text}</p></div>}
